### ISSUE TITLE
Wrong attribute 'response'

### ISSUE THREAD

**Issue by soumyaray** [soafloggers/movlog-api#3]
On this line: https://github.com/soafloggers/movlog-api/blob/continuous_deployment/app.rb#L27

You are looking at a `movie.response`, but i don't think there is such an attribute for `movie`.

**Comment by z58085111** [comment]
Hi Prof. soumya
Thanks for you help! We fixed it.
The attribute 'response' seems to be lost when we merge our code.
Thank you so much
