### ISSUE TITLE
[Services: SearchMovies] search_movies doesn't have left()

### ISSUE THREAD

**Issue by rjollet** [soafloggers/movlog-api#7]

**Comment by NicholasDanks** [comment]
I am not sure if this service needs to be so complicated and have steps. If no left is required, perhaps it could be 1 step (Ie no steps?)

**Comment by z58085111** [comment]
Right. It can be done in 1 step. Thank you!

**Comment by z58085111** [comment]
We refactored the code of SearchMovies. The code will search movies from database firstly. But if there was no related movies, it will try to find movies from OMDB API and return 404 when it cannot find anything.
